**Importing Required Libraries**

In [14]:
import pandas as pd
import numpy as np
import requests
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler,PolynomialFeatures
from sklearn.linear_model import LinearRegression,Ridge
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import cross_val_score,train_test_split

In [18]:
#Download the dataset to this lab environment
def download(url, filename):
    r = requests.get(url)
    if r.status_code == 200:
        with open(filename, "wb") as f:
            f.write(r.content)
        print("File downloaded successfully.")
    else:
        print("File not downloaded. Status Code:", r.status_code)

In [17]:
url = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-Coursera/medical_insurance_dataset.csv'       
filename = "insurance.csv"
download(url, filename)

File downloaded successfully.

In [19]:
df = pd.read_csv("insurance.csv")

In [20]:
df.head()

   19  1    27.9  0 1.1  3    16884.924
0  18  2  33.770  1   0  4   1725.55230
1  28  2  33.000  3   0  4   4449.46200
2  33  2  22.705  0   0  1  21984.47061
3  32  2  28.880  0   0  1   3866.85520
4  31  1  25.740  0   ?  4   3756.62160

In [21]:
#add the headers to the dataframe 
headers = ["age", "gender", "bmi", "no_of_children", "smoker", "region", "charges"]
df.columns = headers

In [22]:
df.head()

  age  gender     bmi  no_of_children smoker  region      charges
0  18       2  33.770               1      0       4   1725.55230
1  28       2  33.000               3      0       4   4449.46200
2  33       2  22.705               0      0       1  21984.47061
3  32       2  28.880               0      0       1   3866.85520
4  31       1  25.740               0      ?       4   3756.62160